#include "report_chart.h"

namespace dl {
std::string reportChartScript(bool english) {
    return std::string("<script>(()=>{const en=") + (english ? "true" : "false") + R"JS(;
'use strict';
const figures=[...document.querySelectorAll('.signal-chart')].filter(f=>f.querySelector('.chart-data'));
if(!figures.length)return;
const charts=figures.map(f=>({f,svg:f.querySelector('svg'),d:JSON.parse(f.querySelector('.chart-data').textContent)}));
let lo=Math.min(...charts.map(c=>c.d.start)),hi=Math.max(...charts.map(c=>c.d.end)),range=[lo,hi],drag=null;
const style=document.createElement('style');style.textContent='.chart-tools{display:flex;flex-wrap:wrap;gap:12px;align-items:center;margin:12px 0}.chart-tools button{padding:8px 16px;font:inherit}.chart-hover{display:none;position:fixed;z-index:1000;max-width:460px;background:#fff;color:#223043;border:1px solid #94a3b8;padding:10px;box-shadow:0 3px 12px #0003;white-space:pre-wrap;pointer-events:none;font:13px monospace}.chart-selection{fill:#2563eb22;stroke:#2563eb;pointer-events:none}.selected-event{outline:3px solid #dc2626}.signal-chart svg{touch-action:none}.chart-range-note{font-size:13px}';document.head.append(style);
const tools=document.createElement('div');tools.className='chart-tools';const reset=document.createElement('button');reset.type='button';reset.textContent=en?'Reset full range':'恢复全范围';tools.append(reset);const label=document.createElement('span');label.className='chart-range-note';tools.append(label);figures[0].before(tools);
const tip=document.createElement('div');tip.className='chart-hover';document.body.append(tip);
const format=(t,relative=false)=>relative?Math.round(t)+' s':new Date(Math.round(t)*1000).toISOString().slice(0,19).replace('T',' ');
const lower=(a,t)=>{let l=0,r=a.length;while(l<r){const m=(l+r)>>>1;if(a[m][0]<t)l=m+1;else r=m;}return l;};
const nearest=(a,t)=>{let i=lower(a,t);if(i===a.length)i--;else if(i&&t-a[i-1][0]<=a[i][0]-t)i--;if(i<0||Math.abs(a[i][0]-t)>600)return null;const time=a[i][0];while(i&&a[i-1][0]===time)i--;return a[i];};
const element=(name,attrs={})=>{const e=document.createElementNS('http://www.w3.org/2000/svg',name);for(const [k,v]of Object.entries(attrs))e.setAttribute(k,v);return e;};
const clamp=(a,b)=>{if(hi<=lo)return [lo,hi];const width=Math.max(1,Math.min(hi-lo,b-a));a=Math.max(lo,Math.min(hi-width,a));return [Math.round(a),Math.round(a+width)];};
const message=()=>{label.textContent=format(range[0],charts[0].d.relative)+' → '+format(range[1],charts[0].d.relative)+' · '+(en?'Wheel: zoom; Shift+wheel/middle-drag: pan. Chart/event display only; exported findings retain their original analysis scope.':'滚轮缩放；Shift+滚轮/中键拖动平移。选区联动图表和事件显示；已导出结论保留原分析范围。');};
function render(){message();for(const c of charts){const svg=c.svg,d=c.d;if(!svg)continue;let old=svg.querySelector('.interactive-curves');if(old)old.remove();for(const g of svg.querySelectorAll('g[fill]'))g.style.display='none';
    const g=element('g',{class:'interactive-curves'});svg.append(g);let n=0;
    for(const data of [d.points,d.second]){const from=lower(data,range[0]);let to=lower(data,range[1]);while(to<data.length&&data[to][0]===range[1])to++;const visible=data.slice(from,to);const points=[];
        if(visible.length<=8194)points.push(...visible);else{const buckets=new Map;for(let i=0;i<visible.length;i++){const p=visible[i],k=Math.min(4095,Math.floor((p[0]-range[0])/Math.max(1,range[1]-range[0])*4096));let b=buckets.get(k);if(!b){b={min:i,max:i};buckets.set(k,b);}if(p[1]<visible[b.min][1])b.min=i;if(p[1]>visible[b.max][1])b.max=i;}const indices=new Set([0,visible.length-1]);for(const b of buckets.values()){indices.add(b.min);indices.add(b.max);}for(const i of [...indices].sort((a,b)=>a-b))points.push(visible[i]);}
        const gaps=[];for(let i=1;i<visible.length;i++)if(visible[i][0]-visible[i-1][0]>(d.gap??600))gaps.push([visible[i-1][0],visible[i][0]]);let path='',previous=null,gap=0;const color=n?'#008300':d.color;
        for(let i=0;i<points.length;i++){const p=points[i],x=64+(p[0]-range[0])/Math.max(1,range[1]-range[0])*750,y=246-(Math.max(d.low,Math.min(d.high,p[1]))-d.low)/(d.high-d.low)*228;while(gap<gaps.length&&previous!==null&&gaps[gap][0]<previous)gap++;const begin=previous===null||(gap<gaps.length&&gaps[gap][0]<p[0]);path+=(begin?'M':'L')+x.toFixed(2)+','+y.toFixed(2)+' ';if(begin||points.length<=60||i===points.length-1)g.append(element('circle',{cx:x,cy:y,r:points.length===1?4:2.5,fill:color}));previous=p[0];}
        g.append(element('path',{d:path,fill:'none',stroke:color,'stroke-width':1.8,'stroke-dasharray':n?'7 4':'','stroke-linejoin':'round'}));n++;}
    let ticks=svg.querySelector('.interactive-ticks');if(ticks)ticks.remove();ticks=element('g',{class:'interactive-ticks'});svg.append(ticks);for(const t of svg.querySelectorAll('text[y="268"]'))t.style.display='none';for(let i=0;i<=4;i++){const x=64+750*i/4,t=range[0]+(range[1]-range[0])*i/4;let text=element('text',{class:'chart-label',x,y:268,'text-anchor':i===0?'start':i===4?'end':'middle'});const time=format(t,d.relative),split=d.relative?-1:time.indexOf(' ');let a=element('tspan');a.textContent=split<0?time:time.slice(0,split);text.append(a);if(split>=0){let b=element('tspan',{x,dy:17});b.textContent=time.slice(split+1);text.append(b);}ticks.append(text);}
    for(const band of svg.querySelectorAll('.outage-band')){const a=Number(band.dataset.eventStart),b=Number(band.dataset.eventEnd);band.style.display=b<range[0]||a>range[1]?'none':'';band.setAttribute('x',64+(Math.max(a,range[0])-range[0])/Math.max(1,range[1]-range[0])*750);band.setAttribute('width',Math.max(1.5,(Math.min(b,range[1])-Math.max(a,range[0]))/Math.max(1,range[1]-range[0])*750));}}
    for(const row of document.querySelectorAll('tr[data-event-start]'))row.hidden=Number(row.dataset.eventEnd)<range[0]||Number(row.dataset.eventStart)>range[1];}
function update(a,b){range=clamp(a,b);render();}
reset.onclick=()=>{range=[lo,hi];render();};
function position(c,e){const p=c.svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform(c.svg.getScreenCTM().inverse());}
function eventSelect(band){for(const row of document.querySelectorAll('tr[data-event-start]')){const match=row.dataset.eventStart===band.dataset.eventStart;row.classList.toggle('selected-event',match);if(match)row.scrollIntoView({block:'center',behavior:'smooth'});}}
for(const c of charts){const svg=c.svg;if(!svg)continue;svg.addEventListener('wheel',e=>{const p=position(c,e);if(p.x<64||p.x>814||p.y<18||p.y>246)return;e.preventDefault();const width=range[1]-range[0],t=range[0]+(p.x-64)/750*width;if(e.shiftKey){update(range[0]+Math.sign(e.deltaY)*width*.15,range[1]+Math.sign(e.deltaY)*width*.15);}else{const factor=e.deltaY<0?.8:1.25;update(t-(t-range[0])*factor,t+(range[1]-t)*factor);}}, {passive:false});
    svg.addEventListener('pointerdown',e=>{const p=position(c,e);if(p.x<64||p.x>814||p.y<18||p.y>246||!(e.button===0||e.button===1))return;drag={c,x:p.x,last:p.x,range:[...range],middle:e.button===1,band:e.target.closest('.outage-band')};try{svg.setPointerCapture(e.pointerId);}catch(_){}e.preventDefault();tip.style.display='none';});
    svg.addEventListener('pointermove',e=>{const p=position(c,e);if(drag&&drag.c===c){drag.last=Math.max(64,Math.min(814,p.x));let rect=svg.querySelector('.chart-selection');if(!rect){rect=element('rect',{class:'chart-selection',y:18,height:228});svg.append(rect);}rect.setAttribute('x',Math.min(drag.x,drag.last));rect.setAttribute('width',Math.abs(drag.last-drag.x));return;}if(p.x<64||p.x>814||p.y<18||p.y>246){tip.style.display='none';return;}
        const time=range[0]+(p.x-64)/750*(range[1]-range[0]);let text=format(time,c.d.relative);for(const other of charts){const title=other.f.querySelector('strong').textContent;
            if(other.d.periods?.length){let i=lower(other.d.periods,time);if(i===other.d.periods.length||other.d.periods[i][0]>time)i--;const period=other.d.periods[i];text+='\n'+title+': '+(period&&time<=period[1]?(period[2]?period[3]/other.d.scale+' '+other.d.unit+' · P50 (n='+period[2]+')':(en?'No samples':'无采样'))+' · '+format(period[0])+' → '+format(period[1]):(en?'Outside periods':'不在统计时期内'));continue;}
            const matched=[];for(let index=0;index<2;index++){const data=index?other.d.second:other.d.points;if(!data.length&&index&&!other.d.compare)continue;const point=nearest(data,time);matched[index]=point;const prefix=other.d.compare?(index?'B ':'A '):'';text+='\n'+prefix+title+': '+(point?(point[1]/other.d.scale)+' '+other.d.unit+' · '+format(point[0]+(other.d.relative?(index?other.d.secondStart:other.d.originalStart):0)):(en?'No nearby sample':'附近无采样'));}
            if(other.d.compare&&matched[0]&&matched[1])text+='\nΔ(B−A) '+title+': '+((matched[1][1]-matched[0][1])/other.d.scale)+' '+other.d.unit;}

        tip.textContent=text;tip.style.display='block';tip.style.left=Math.max(4,Math.min(e.clientX+14,innerWidth-tip.offsetWidth-8))+'px';tip.style.top=Math.max(4,Math.min(e.clientY+14,innerHeight-tip.offsetHeight-8))+'px';});
    svg.addEventListener('pointerup',e=>{if(!drag||drag.c!==c)return;const d=drag;drag=null;svg.querySelector('.chart-selection')?.remove();if(svg.hasPointerCapture(e.pointerId))svg.releasePointerCapture(e.pointerId);const delta=(d.last-d.x)/750*(d.range[1]-d.range[0]);if(d.middle){update(d.range[0]-delta,d.range[1]-delta);}else if(Math.abs(d.last-d.x)>=6){let a=d.range[0]+(Math.min(d.x,d.last)-64)/750*(d.range[1]-d.range[0]),b=d.range[0]+(Math.max(d.x,d.last)-64)/750*(d.range[1]-d.range[0]);update(a,b);}else if(d.band)eventSelect(d.band);});
    svg.addEventListener('pointercancel',()=>{drag=null;svg.querySelector('.chart-selection')?.remove();});svg.addEventListener('pointerleave',()=>{tip.style.display='none';});
    for(const band of svg.querySelectorAll('.outage-band'))band.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();eventSelect(band);}});}
document.addEventListener('keydown',e=>{if(e.key==='Escape'){drag=null;for(const c of charts)c.svg?.querySelector('.chart-selection')?.remove();tip.style.display='none';}if(e.ctrlKey&&e.key==='0'){e.preventDefault();reset.click();}});
message();
})();</script>)JS";
}
}  // namespace dl
