#!/usr/bin/env python3
"""Generate the offline C++ catalog; IDs remain stable when new entries are appended."""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
entries = json.loads((ROOT / 'resources/i18n/ui.json').read_text())
entries += json.loads((ROOT / 'resources/i18n/generated.json').read_text())
seen = set()
spec = re.compile(r'%(?:[-+ #0]*\d*(?:\.\d+)?(?:ll|l|z)?[diuoxXfFeEgGcs]|%)')
for entry in entries:
    assert entry['id'] not in seen, entry['id']
    seen.add(entry['id'])
    assert entry['en'], entry['id']
    assert spec.findall(entry['zh']) == spec.findall(entry['en']), entry['id']

def literal(text):
    return json.dumps(text, ensure_ascii=False).replace('\\u0000', '\\000')

ids = '// Generated by tools/build_text_catalog.py; edit resources/i18n/ui.json.\n#pragma once\nnamespace dl { enum class TextId {\n'
ids += ''.join('    ' + e['id'] + ',\n' for e in entries) + '}; }\n'
rows = '// Generated offline catalog.\n'
rows += ''.join('{' + ','.join([literal(e['zh']), literal(e['en']), 'L'+literal(e['zh']), 'L'+literal(e['en'])]) + '},\n' for e in entries)
for relative, content in [('src/presentation/text_ids.h', ids), ('src/presentation/text_catalog.inc', rows)]:
    path = ROOT / relative
    if '--check' in sys.argv:
        assert path.read_text() == content, relative + ' is stale'
    else:
        path.write_text(content)
print(f'{len(entries)} bilingual UI entries validated')
